
vertical_whitespace:
  max_empty_lines: 3

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

disabled_rules: # rule identifiers to exclude from running
#  - vertical_whitespace
  - nesting
  - force_cast
  - leading_whitespace
  - unused_closure_parameter
  - empty_parentheses_with_trailing_closure
  - empty_enum_arguments
  - identifier_name
  - class_delegate_protocol
  - fallthrough
  - type_name
  - no_fallthrough_only
  - redundant_optional_initialization
  - multiple_closures_with_trailing_closure
  - unused_setter_value
  - weak_delegate
  - orphaned_doc_comment
  - comment_spacing
  - inclusive_language
  - unused_capture_list

cyclomatic_complexity:
  - 20 # warning
  - 25 # error

line_length:
#  - 160 # warning
  - 200 # error

function_body_length:
  - 120 # warning
  - 200 # error

type_body_length:
  - 350 # warning

file_length:
  - 600 # warning
  - 900 # error

